# Assignment: Libraries- NumPy & Pandas

### Q1.  Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.

#### Answer: 

Steps:
1. Load the retail sales dataset using pandas.
2. Display the first 5 rows to get preview of the data.
3. Use ```.info()``` to understand the dataset structure, including:
   - Column names
   - Data types
   - Non-null values

In [10]:
# Importing pandas
import pandas as pd

In [14]:
# Loading the dataset
df = pd.read_csv("retail_dataset .csv")

In [13]:
# Displaying first few rows properly
(df.head())

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [15]:
# Displaying dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

### Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.

#### Answer: 
Steps:
1. Check for missing values in each column using `.isnull()`.
2. Count the number of missing values column-wise.
3. Calculate the total missing values in the entire dataset.

In [30]:
# Checking missing values in each column and adding them to find the total number of missing values per column.
missing_per_column = df.isnull().sum()
print(missing_per_column)

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [23]:
# Ensure this line exists before your sum
missing_per_column = df.isnull().sum() 
total_missing = missing_per_column.sum()
print("Total missing values in dataset:", total_missing)

Total missing values in dataset: 12

### Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.

#### Answer:

Steps:

1. Calculate the mean of Quantity and Price columns.
2. Replace missing values `NaN` with their respective mean using `.fillna().`
3. To verify change check missing values in Quantity and Price columns.

In [31]:
# Calculating the mean of Quantity and Price columns and replace missing values with their respective mean using.
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [32]:
#  verifying changes.
print("Missing values after replacement:")
print(df[['Quantity', 'Price']].isnull().sum())

Missing values after replacement:
Quantity    0
Price       0
dtype: int64

### Q4. Remove all rows where the Product Category or Region column contains missing values.

#### Answer: 
Steps:
1. Identify rows where Product Category or Region has missing values.
2. Remove those rows using `.dropna()`.
3. To verify change check missing values in Product Category and Region column.

We use the `subset` parameter to target only specific columns instead of the entire dataset.

In [75]:
# Drop rows where 'Product Category' or 'Region' has missing values
df_cleaned = df.dropna(subset=['Product Category', 'Region'])

In [102]:
print("Missing values after removal:")
print(df_cleaned[['Product Category', 'Region']].isnull().sum())

Missing values after removal:
Product Category    0
Region              0
dtype: int64

### Q5. Create a new column called Revenue using NumPy, where: Revenue = Quantity × Price ; Display the updated dataset with the new column.

#### Answer :

steps:

1. Use NumPy to create a new column called **Revenue**.
2. Apply the formula: Revenue = Quantity × Price
3. Add this new column to the dataset.

In [39]:
import numpy as np

In [83]:
df = df.dropna(subset=['Product Category', 'Region'])

In [84]:
# Createing Revenue column.
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

In [85]:
# Displaying updated dataset
print("Dataset with Revenue column:")
(df.head())

Dataset with Revenue column:

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue,Month
0,T001,C015,Books,7.0,167.0,2023-02-02,North,1169.0,2
1,T002,C004,Toys,4.0,374.0,2023-02-17,South,1496.0,2
2,T003,C033,Furniture,8.0,1059.0,2024-05-17,South,8472.0,5
3,T004,C047,Groceries,5.0,304.0,2024-02-11,South,1520.0,2
4,T005,C022,Books,7.0,282.0,2024-07-27,West,1974.0,7

### Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.

#### Answer:

In [86]:
# Calculateing total revenue using NumPy
total_revenue = np.sum(df['Revenue'])
print("Total Revenue:")
print(total_revenue)

Total Revenue:
465529.66058002145

### Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.

#### Answers:

steps:

1. Group the dataset by Product Category.
2. Round off SUM value up to two decimal places for cleaner value and then print the values for categorycal revanue sum.

In [87]:
# Grouping by Product Category and calculateing total revenue.

category_revenue = df.groupby('Product Category')['Revenue'].sum()

# rounding off up to two decimal points for cleaner value and then printing the values for categorycal revanue sum.

category_revenue = category_revenue.round(2)
print(category_revenue)

Product Category
Beauty          27647.00
Books           29597.94
Clothing        85006.00
Electronics     93204.32
Furniture      129664.53
Groceries       11978.00
Sports          34484.00
Toys            53947.88
Name: Revenue, dtype: float64

### Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.

#### Answer:

steps:

1. Short table in Decending order of category revanue.
2. To get top 3 categories with highest revenue print top 3 rows of the shorted table.
3. To get Bottom 3 categories with lowest revenue print last 3 rows of the shorted table.

In [88]:
# Short table in Decending order of category revanue.
sorted_revenue = category_revenue.sort_values(ascending=False)

In [89]:
# To get top 3 categories with highest revenue print top 3 rows of the shorted table.
top_3 = sorted_revenue.head(3)
print("Top 3 Categories by Revenue:")
print(top_3)

Top 3 Categories by Revenue:
Product Category
Furniture      129664.53
Electronics     93204.32
Clothing        85006.00
Name: Revenue, dtype: float64

In [90]:
# To get Bottom 3 categories with lowest revenue print last 3 rows of the shorted table.
bottom_3 = sorted_revenue.tail(3)
print("\nBottom 3 Categories by Revenue:")
print(bottom_3)

Bottom 3 Categories by Revenue:
Product Category
Books        29597.94
Beauty       27647.00
Groceries    11978.00
Name: Revenue, dtype: float64

### Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue.

#### Answer:

steps:

1. Group the dataset by Region.
2. Calculate the total revenue for each region.
3. Short table in Decending order of region vise revanue.
4. Identify the region with the highest revenue (First row).
5. Identify the region with the lowest revenue (Last row).

In [91]:
# step-1:
region_revenue = df.groupby('Region')['Revenue'].sum().round(2)
print("Revenue by Region:")
print(region_revenue)

Revenue by Region:
Region
East     126232.04
North    153244.35
South    104855.74
West      81197.53
Name: Revenue, dtype: float64

In [92]:
# step-2:
highest_region = region_revenue.idxmax()
print("Region with Highest Revenue:", highest_region)

Region with Highest Revenue: North

In [93]:
# step-3:
lowest_region = region_revenue.idxmin()
print("Region with Lowest Revenue:", lowest_region)

Region with Lowest Revenue: West

### Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy.

#### Answer:

steps:

1. Converting Date column correctly (day first format) to Convert Date column to datetime formate.
2. Extract the month from the Date column.
3. Group the dataset by month and calculate total monthly revenue.
4. Print month vise total revenue.
5. Calculate the mean, median, and standard deviation of the Revenue column using NumPy.

In [94]:
# step-1:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

In [95]:
# step-2:
df['Month'] = df['Date'].dt.month

In [96]:
# step-3:
monthly_revenue = df.groupby('Month')['Revenue'].sum()

In [97]:
# step-4:
print("Monthly Revenue:")
print(monthly_revenue)

Monthly Revenue:
Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64

In [98]:
# step-5:
mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])


print("Mean:", (mean_revenue))
print("Median:", (median_revenue))
print("Standard Deviation:",(std_revenue))

Mean: 4900.312216631804
Median: 3282.1052631578946
Standard Deviation: 4721.171795257337